version: '3.8'

services:

  catalog_db:
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db


  basket_db:
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379
    
    
  discount_db:
    container_name: discount_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=discount_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"


  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"


  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin


  catalog_api:
    container_name: catalog_api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalog_db
    ports:
      - "8000:80"


  basket_api:
    container_name: basket_api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basket_db:6379"
      - "GrpcSettings:DiscountUrl=http://discount_grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basket_db
      - rabbitmq
    ports:
      - "8001:80"


  discount_api:
    container_name: discount_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discount_db;Port=5432;Database=discount_db;User Id=admin;Password=admin1234;"
    depends_on:
      - discount_db
    ports:
      - 8002:80
  

  discount_grpc:
    container_name: discount_grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discount_db;Port=5432;Database=discount_db;User Id=admin;Password=admin1234;"
    depends_on:
      - discount_db
    ports:
      - "8003:80"


  ordering_api:
    container_name: ordering_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678"  
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
        - orderdb
        - rabbitmq
    ports:
        - "8004:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - catalog_api
        - basket_api
        - discount_api
        - ordering_api
    ports:
      - "8010:80"

  shopping_aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog_api"
      - "ApiSettings:BasketUrl=http://basket_api"
      - "ApiSettings:OrderingUrl=http://ordering_api"
    depends_on:
      - catalog_api
      - basket_api
      - ordering_api
    ports:
      - "8005:80"
