version: '3.8'

services:

  catalog_db:
    image: mongo

  basket_db:
    image: redis

  discount_db:
    image: postgres 

  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4
  
  catalog_api:
    image: catalog_api
    build: 
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket_api:
    image: basket_api
    build: 
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount_api:
    image: discount_api
    build: 
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount_grpc:
    image: discount_grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

  ordering_api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

  shopping_aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile


volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
