version: '3.8'

services:

  catalog_db:
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db


  basket_db:
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379
    
    
  discount_db:
    container_name: discount_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=discount_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin


  catalog_api:
    container_name: catalog_api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalog_db
    ports:
      - "8000:80"


  basket_api:
    container_name: basket_api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basket_db:6379"
    depends_on:
      - basket_db
    ports:
      - "8001:80"

  discount_api:
    container_name: discount_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discount_db;Port=5432;Database=discount_db;User Id=admin;Password=admin1234;"
    depends_on:
      - discount_db
    ports:
      - 8002:80