version: '3.8'

services:

  catalog_db:
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db


  basket_db:
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379
    
  
  catalog_api:
    container_name: catalog_api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalog_db
    ports:
      - "8000:80"


  basket_api:
    container_name: basket_api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basket_db:6379"
    depends_on:
      - basket_db
    ports:
      - "8001:80"