version: '3.8'

services:

  catalog_db:
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db


  basket_db:
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379
    
    
  discount_db:
    container_name: discount_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=discount_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"


  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"


  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin


  catalog_api:
    container_name: catalog_api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - catalog_db
    ports:
      - "8000:80"


  basket_api:
    container_name: basket_api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basket_db:6379"
      - "GrpcSettings:DiscountUrl=http://discount_grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - basket_db
      - rabbitmq
    ports:
      - "8001:80"


  discount_api:
    container_name: discount_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discount_db;Port=5432;Database=discount_db;User Id=admin;Password=admin1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - discount_db
    ports:
      - 8002:80
  

  discount_grpc:
    container_name: discount_grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discount_db;Port=5432;Database=discount_db;User Id=admin;Password=admin1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - discount_db
    ports:
      - "8003:80"


  ordering_api:
    container_name: ordering_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678"  
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
        - orderdb
        - rabbitmq
    ports:
        - "8004:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
        - catalog_api
        - basket_api
        - discount_api
        - ordering_api
    ports:
      - "8010:80"

  shopping_aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog_api"
      - "ApiSettings:BasketUrl=http://basket_api"
      - "ApiSettings:OrderingUrl=http://ordering_api"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - catalog_api
      - basket_api
      - ordering_api
    ports:
      - "8005:80"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601" 

  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://catalog.api/hc
      - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://basket.api/hc
      - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
      - HealthChecksUI__HealthChecks__2__Uri=http://discount.api/hc
      - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
      - HealthChecksUI__HealthChecks__3__Uri=http://ordering.api/hc
      - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
      - HealthChecksUI__HealthChecks__4__Uri=http://shopping.aggregator/hc
      - HealthChecksUI__HealthChecks__5__Name=AspnetRunBasics WebMVC Health Check
      - HealthChecksUI__HealthChecks__5__Uri=http://aspnetrunbasics/hc
    ports:
      - "8007:80"
